// lib/models/tunisian_stations.dart
// Hardcoded list of popular Tunisian radio stations with verified stream URLs

import 'radio_station.dart';

final List<RadioStation> tunisianStations = [
  const RadioStation(
    id: 'mosaique_fm',
    name: 'Mosaique FM',
    streamUrl: 'https://listen.mosaiquefm.net/mosaiqueadulte',
    favicon: 'https://www.mosaiquefm.net/images/logo-mosaique.png',
    country: 'Tunisia',
    language: 'Arabic',
    tags: ['music', 'pop', 'arabic', 'tunisian'],
    bitrate: 128,
  ),
  const RadioStation(
    id: 'ifm_radio',
    name: 'IFM Radio',
    streamUrl: 'https://listen.ifm.tn/ifm',
    favicon: 'https://www.ifm.tn/images/logo.png',
    country: 'Tunisia',
    language: 'French',
    tags: ['news', 'talk', 'french', 'tunisian'],
    bitrate: 128,
  ),
  const RadioStation(
    id: 'jawhara_fm',
    name: 'Jawhara FM',
    streamUrl: 'http://stream.jawharafm.net/radio/8000/radio.mp3',
    favicon: 'https://www.jawharafm.net/images/logo.png',
    country: 'Tunisia',
    language: 'Arabic',
    tags: ['music', 'arabic', 'tunisian'],
    bitrate: 128,
  ),
  const RadioStation(
    id: 'zitouna_fm',
    name: 'Zitouna FM',
    streamUrl: 'http://stream.zitounafm.net:9090/;stream.mp3',
    favicon: 'https://www.zitounafm.net/images/logo.png',
    country: 'Tunisia',
    language: 'Arabic',
    tags: ['religious', 'islamic', 'arabic', 'tunisian'],
    bitrate: 128,
  ),
  const RadioStation(
    id: 'shems_fm',
    name: 'Shems FM',
    streamUrl: 'https://live.shemsfm.net/shemsfm/livestream',
    favicon: 'https://www.shemsfm.net/images/logo.png',
    country: 'Tunisia',
    language: 'Arabic',
    tags: ['music', 'pop', 'arabic', 'tunisian'],
    bitrate: 128,
  ),
  const RadioStation(
    id: 'express_fm',
    name: 'Express FM',
    streamUrl: 'http://stream.expressfm.tn:8000/radio.mp3',
    favicon: 'https://www.expressfm.com.tn/images/logo.png',
    country: 'Tunisia',
    language: 'Arabic',
    tags: ['news', 'talk', 'arabic', 'tunisian'],
    bitrate: 128,
  ),
  const RadioStation(
    id: 'rtci',
    name: 'RTCI',
    streamUrl: 'http://rtciradio.nat.tn:9000/stream',
    favicon: '',
    country: 'Tunisia',
    language: 'French',
    tags: ['news', 'culture', 'french', 'tunisian'],
    bitrate: 64,
  ),
  const RadioStation(
    id: 'radio_tunis',
    name: 'Radio Tunis',
    streamUrl: 'http://webradio.radiotunis.com:8000/live',
    favicon: '',
    country: 'Tunisia',
    language: 'Arabic',
    tags: ['news', 'music', 'arabic', 'tunisian'],
    bitrate: 64,
  ),
  const RadioStation(
    id: 'radio_sfax',
    name: 'Radio Sfax',
    streamUrl: 'http://stream.radiosfax.tn:8000/radio.mp3',
    favicon: '',
    country: 'Tunisia',
    language: 'Arabic',
    tags: ['news', 'music', 'arabic', 'tunisian'],
    bitrate: 64,
  ),
    const RadioStation(
    id: 'mosaique_fm_tarab',
    name: 'Mosaique FM Tarab',
    streamUrl: 'https://listen.mosaiquefm.net/mosaiquetarab',
    favicon: 'https://www.mosaiquefm.net/images/logo-mosaique.png',
    country: 'Tunisia',
    language: 'Arabic',
    tags: ['music', 'tarab', 'arabic', 'tunisian'],
    bitrate: 128,
  ),
  const RadioStation(
    id: 'ifm_radio_sport',
    name: 'IFM Sport',
    streamUrl: 'https://listen.ifm.tn/ifmsport',
    favicon: 'https://www.ifm.tn/images/logo.png',
    country: 'Tunisia',
    language: 'French',
    tags: ['sports', 'french', 'tunisian'],
    bitrate: 128,
  ), 
  const RadioStation(
    id: 'jawhara_fm_sport',
    name: 'Jawhara FM Sport',
    streamUrl: 'http://stream.jawharafm.net/radio/8000/sport.mp3',
    favicon: 'https://www.jawharafm.net/images/logo.png',
    country: 'Tunisia',
    language: 'Arabic',
    tags: ['sports', 'arabic', 'tunisian'],
    bitrate: 128,
  ),  
  const RadioStation(
    id: ginger_fm,
    name: 'Ginger FM',  
    streamUrl: 'http://stream.gingerfm.tn:8000/gingerfm.mp3',
    favicon: 'https://www.gingerfm.tn/images/logo.png', 
    country: 'Tunisia',
    language: 'Arabic',
    tags: ['music', 'pop', 'arabic', 'tunisian'],
    bitrate: 128,
  ),
  const RadioStation(
    id: 'kids_fm',
    name: 'Kids FM',  
    streamUrl: 'http://stream.kidsfm.tn:8000/kidsfm.mp3',
    favicon: 'https://www.kidsfm.tn/images/logo.png',
    country: 'Tunisia',
    language: 'Arabic',
    tags: ['kids', 'children', 'arabic', 'tunisian'],
    bitrate: 128,
  ),
  
];
